//! fz-70q (B3) — selective-receive matcher fn codegen.
//!
//! Emits the leaf matcher fn for a `Term::ReceiveMatched`. The matcher
//! ABI matches `fz_runtime::park::MatcherFn` (see runtime/src/park.rs):
//!
//! ```text
//! extern "C" fn(msg: u64, pinned: *const u64, out: *mut u64) -> u32
//! ```
//!
//! - `msg`: candidate message (raw FzValue bits).
//! - `pinned`: pointer to `[u64; n_pinned]` with each `^name`'s value
//!   bits, in the order they appear in `Term::ReceiveMatched::pinned`.
//! - `out`: caller-supplied `[u64; bound_arity]` scratch buffer; the
//!   matcher writes the winning clause's bound-var values here.
//! - returns `0` on miss; `k > 0` is the 1-based clause index (caller
//!   indexes `clause_bodies[k-1]`).
//!
//! Semantic spec: `src/ir_interp.rs::try_match_pattern` (now the
//! PerRow leaf sub-routine for the Decision-driven walker).
//!
//! Production codegen consumes the cached AST-free `Matcher` attached to
//! `Term::ReceiveMatched`; it does not rebuild a Matrix/Decision from receive
//! clauses. The older Decision emitter remains temporarily for migration tests
//! while the remaining fallback-only shapes are deleted.

#![allow(dead_code)]

use crate::ast::Pattern;
use crate::fz_ir::{Module, ReceiveClause, Var};
use crate::ir_codegen::{
    CodegenError, EMPTY_LIST_BITS, HEADER_SIZE, NIL_BITS, SLOT_BYTES, TAG_ATOM, TAG_INT, TAG_MASK,
    TAG_PTR, TRUE_BITS, emit_fn_body,
};
use crate::matcher::{Matcher, MatcherConst, MatcherNode, MatcherTest};
use crate::pattern_matrix::{
    BodyId, Decision, Matrix, Row, SubjectRef, SwitchKey, SwitchKind, compile as compile_matrix,
};
use cranelift_codegen::ir::{
    self, AbiParam, InstBuilder, MemFlags, Signature, condcodes::IntCC, types,
};
use cranelift_codegen::isa::CallConv;
use cranelift_frontend::{FunctionBuilder, FunctionBuilderContext};
use cranelift_module::{DataDescription, DataId, FuncId, Linkage};
use std::collections::HashMap;

/// Cranelift signature for the matcher fn family. Matches
/// `fz_runtime::park::MatcherFn`.
pub(crate) fn matcher_signature() -> Signature {
    let mut sig = Signature::new(CallConv::SystemV);
    sig.params.push(AbiParam::new(types::I64)); // msg
    sig.params.push(AbiParam::new(types::I64)); // pinned_ptr
    sig.params.push(AbiParam::new(types::I64)); // out_ptr
    sig.returns.push(AbiParam::new(types::I32));
    sig
}

/// Declare a matcher fn in `module`. The caller is responsible for
/// pairing this with a single `emit_matcher_body` call before finalize.
pub(crate) fn declare_matcher<M: cranelift_module::Module>(
    module: &mut M,
    name: &str,
) -> Result<FuncId, CodegenError> {
    module
        .declare_function(name, Linkage::Local, &matcher_signature())
        .map_err(|e| CodegenError::new(format!("declare {}: {}", name, e)))
}

/// fz-puj.20 (H9 / E2) — Decision-driven matcher body emitter.
///
/// Same ABI as `emit_matcher_body`, but the body is generated by walking
/// a `pattern_matrix::Decision` instead of cascading per-clause AST walks.
/// Switch nodes share constructor tests across all clauses with the same
/// top-level constructor (not just adjacent same-arity tuples like the
/// peephole). Pinned and Map/Bitstring patterns drop to PerRow, which
/// falls back to the existing per-row `compile_pattern` walker.
///
/// This emitter has no production caller yet — production wiring lands in
/// fz-puj.21 (AOT) and fz-puj.22 (interp). Tests exercise it end-to-end.
pub(crate) fn emit_matcher_body_from_decision<M: cranelift_module::Module>(
    module: &mut M,
    fbctx: &mut FunctionBuilderContext,
    matcher_id: FuncId,
    fz_module: &Module,
    tuple_schema_ids: &HashMap<usize, u32>,
    pinned: &[(String, Var)],
    clauses: &[ReceiveClause],
    // fz-puj.45 (X4) — `fz_matcher_eq_bytes` FuncId for binary-literal
    // comparison. `None` in unit-test contexts that don't link the
    // runtime; in that mode a Binary pattern will surface a clean
    // CodegenError instead of trying to call an undeclared symbol.
    matcher_eq_bytes_id: Option<FuncId>,
    // fz-puj.47 (X6) — `fz_matcher_map_get` FuncId for map-key lookup.
    // Same None-in-unit-tests contract as matcher_eq_bytes_id.
    matcher_map_get_id: Option<FuncId>,
) -> Result<(), CodegenError> {
    // Guards aren't yet supported (fz-70q.2.2 / fz-puj.42). Reject up
    // front so we never silently accept a half-implemented clause.
    for (i, c) in clauses.iter().enumerate() {
        if c.guard.is_some() {
            return Err(CodegenError::new(format!(
                "matcher clause {} carries a guard; pure-guard support lands in fz-puj.42",
                i
            )));
        }
    }

    // Build N=1 Matrix; compile to Decision.
    let subject_var = Var(0);
    let matrix = Matrix {
        subjects: vec![subject_var],
        rows: clauses
            .iter()
            .enumerate()
            .map(|(i, c)| Row {
                patterns: vec![c.pattern.clone()],
                preconditions: Vec::new(),
                guard: None,
                body_id: i as BodyId,
            })
            .collect(),
    };
    let decision = compile_matrix(matrix);

    let pinned_indices: HashMap<String, usize> = pinned
        .iter()
        .enumerate()
        .map(|(i, (n, _))| (n.clone(), i))
        .collect();
    let bound_indices_per_clause: Vec<HashMap<String, usize>> = clauses
        .iter()
        .map(|c| {
            c.bound_names
                .iter()
                .enumerate()
                .map(|(i, n)| (n.clone(), i))
                .collect()
        })
        .collect();

    // fz-puj.45 (X4) — pre-declare one `.data` symbol per unique Binary
    // literal in the clause set, *before* opening the function builder
    // so we can rely on `module: &mut M` here. Inside the body we'll
    // bind a per-function `GlobalValue` for each one.
    let mut unique_bytes: Vec<Vec<u8>> = Vec::new();
    for c in clauses {
        collect_binary_literals_in_pattern(&c.pattern.node, &mut unique_bytes);
    }
    let mut binary_data_ids: HashMap<Vec<u8>, DataId> = HashMap::new();
    for (idx, bytes) in unique_bytes.into_iter().enumerate() {
        if binary_data_ids.contains_key(&bytes) {
            continue;
        }
        let name = format!(".fz_matcher_bin_{}_{}", matcher_id.as_u32(), idx);
        let did = module
            .declare_data(&name, Linkage::Local, false, false)
            .map_err(|e| CodegenError::new(format!("declare {}: {}", name, e)))?;
        let mut desc = DataDescription::new();
        desc.define(bytes.clone().into_boxed_slice());
        desc.set_align(1);
        module
            .define_data(did, &desc)
            .map_err(|e| CodegenError::new(format!("define {}: {}", name, e)))?;
        binary_data_ids.insert(bytes, did);
    }

    let mut compile_err: Option<CodegenError> = None;
    emit_fn_body(module, fbctx, matcher_signature(), matcher_id, |m, b| {
        let entry = b.create_block();
        b.append_block_params_for_function_params(entry);
        b.switch_to_block(entry);
        b.seal_block(entry);
        let msg = b.block_params(entry)[0];
        let pinned_ptr = b.block_params(entry)[1];
        let out_ptr = b.block_params(entry)[2];

        let miss_block = b.create_block();

        let mut root_values: HashMap<Var, ir::Value> = HashMap::new();
        root_values.insert(subject_var, msg);

        // fz-puj.45 (X4) — per-function bindings: GlobalValue per unique
        // binary literal + FuncRef for the matcher_eq_bytes runtime helper.
        let binary_data_gvs: HashMap<Vec<u8>, ir::GlobalValue> = binary_data_ids
            .iter()
            .map(|(bytes, did)| (bytes.clone(), m.declare_data_in_func(*did, b.func)))
            .collect();
        let matcher_eq_bytes_fref =
            matcher_eq_bytes_id.map(|fid| m.declare_func_in_func(fid, b.func));
        let matcher_map_get_fref =
            matcher_map_get_id.map(|fid| m.declare_func_in_func(fid, b.func));

        let ctx = DecisionCtx {
            fz_module,
            tuple_schema_ids,
            bound_indices_per_clause: &bound_indices_per_clause,
            pinned_indices: &pinned_indices,
            pinned_ptr,
            out_ptr,
            clauses,
            root_values: &root_values,
            binary_data_gvs: &binary_data_gvs,
            matcher_eq_bytes_fref,
            matcher_map_get_fref,
        };

        if let Err(e) = emit_decision(b, &ctx, &decision, miss_block) {
            compile_err = Some(e);
            // fz-puj.48 (X7): finish the body so the surfaced CodegenError
            // reaches the user instead of escalating into a cranelift
            // `remove_constant_phis: entry block unknown` panic. The active
            // block (wherever emit_decision was when it gave up) gets a
            // return; miss_block — created but never terminated — gets
            // jumped to via a fresh predecessor and sealed.
            let zero = b.ins().iconst(types::I32, 0);
            b.ins().return_(&[zero]);
            let to_miss = b.create_block();
            b.switch_to_block(to_miss);
            b.seal_block(to_miss);
            b.ins().jump(miss_block, &[]);
            b.switch_to_block(miss_block);
            b.seal_block(miss_block);
            let zero2 = b.ins().iconst(types::I32, 0);
            b.ins().return_(&[zero2]);
            return;
        }

        // Miss block — every Fail / fall-through lands here.
        b.switch_to_block(miss_block);
        b.seal_block(miss_block);
        let zero = b.ins().iconst(types::I32, 0);
        b.ins().return_(&[zero]);
    })
    .map_err(|e| CodegenError::new(format!("define matcher fn: {}", e)))?;

    if let Some(e) = compile_err {
        return Err(e);
    }
    Ok(())
}

/// Emit the receive ABI matcher directly from the cached AST-free
/// [`Matcher`]. The clause slice is still used for ABI metadata
/// (`bound_names` and guard rejection), but matching control flow comes from
/// `matcher` instead of rebuilding Matrix/Decision from receive patterns.
pub(crate) fn emit_matcher_body_from_matcher<M: cranelift_module::Module>(
    module: &mut M,
    fbctx: &mut FunctionBuilderContext,
    matcher_id: FuncId,
    fz_module: &Module,
    tuple_schema_ids: &HashMap<usize, u32>,
    pinned: &[(String, Var)],
    clauses: &[ReceiveClause],
    matcher: &Matcher,
    matcher_eq_bytes_id: Option<FuncId>,
    matcher_map_get_id: Option<FuncId>,
) -> Result<(), CodegenError> {
    for (i, c) in clauses.iter().enumerate() {
        if c.guard.is_some() {
            return Err(CodegenError::new(format!(
                "matcher clause {} carries a guard; pure-guard support lands in fz-puj.54.12",
                i
            )));
        }
    }

    let pinned_indices: HashMap<String, usize> = pinned
        .iter()
        .enumerate()
        .map(|(i, (n, _))| (n.clone(), i))
        .collect();
    let bound_indices_per_clause: Vec<HashMap<String, usize>> = clauses
        .iter()
        .map(|c| {
            c.bound_names
                .iter()
                .enumerate()
                .map(|(i, n)| (n.clone(), i))
                .collect()
        })
        .collect();

    let mut unique_bytes = Vec::new();
    collect_binary_literals_in_matcher(matcher, &mut unique_bytes);
    let mut binary_data_ids: HashMap<Vec<u8>, DataId> = HashMap::new();
    for (idx, bytes) in unique_bytes.into_iter().enumerate() {
        if binary_data_ids.contains_key(&bytes) {
            continue;
        }
        let name = format!(".fz_matcher_bin_{}_{}", matcher_id.as_u32(), idx);
        let did = module
            .declare_data(&name, Linkage::Local, false, false)
            .map_err(|e| CodegenError::new(format!("declare {}: {}", name, e)))?;
        let mut desc = DataDescription::new();
        desc.define(bytes.clone().into_boxed_slice());
        desc.set_align(1);
        module
            .define_data(did, &desc)
            .map_err(|e| CodegenError::new(format!("define {}: {}", name, e)))?;
        binary_data_ids.insert(bytes, did);
    }

    let mut compile_err: Option<CodegenError> = None;
    emit_fn_body(module, fbctx, matcher_signature(), matcher_id, |m, b| {
        let entry = b.create_block();
        b.append_block_params_for_function_params(entry);
        b.switch_to_block(entry);
        b.seal_block(entry);
        let msg = b.block_params(entry)[0];
        let pinned_ptr = b.block_params(entry)[1];
        let out_ptr = b.block_params(entry)[2];

        let miss_block = b.create_block();
        let binary_data_gvs: HashMap<Vec<u8>, ir::GlobalValue> = binary_data_ids
            .iter()
            .map(|(bytes, did)| (bytes.clone(), m.declare_data_in_func(*did, b.func)))
            .collect();
        let matcher_eq_bytes_fref =
            matcher_eq_bytes_id.map(|fid| m.declare_func_in_func(fid, b.func));
        let matcher_map_get_fref =
            matcher_map_get_id.map(|fid| m.declare_func_in_func(fid, b.func));

        let ctx = MatcherCtx {
            fz_module,
            tuple_schema_ids,
            bound_indices_per_clause: &bound_indices_per_clause,
            pinned_indices: &pinned_indices,
            pinned_ptr,
            out_ptr,
            matcher,
            msg,
            binary_data_gvs: &binary_data_gvs,
            matcher_eq_bytes_fref,
            matcher_map_get_fref,
        };

        let mut state = MatcherEmitState::default();
        if let Err(e) = emit_matcher_node(b, &ctx, matcher.root, miss_block, &mut state) {
            compile_err = Some(e);
            finish_failed_matcher_body(b, miss_block);
            return;
        }

        b.switch_to_block(miss_block);
        b.seal_block(miss_block);
        let zero = b.ins().iconst(types::I32, 0);
        b.ins().return_(&[zero]);
    })
    .map_err(|e| CodegenError::new(format!("define matcher fn: {}", e)))?;

    if let Some(e) = compile_err {
        return Err(e);
    }
    Ok(())
}

struct MatcherCtx<'a> {
    fz_module: &'a Module,
    tuple_schema_ids: &'a HashMap<usize, u32>,
    bound_indices_per_clause: &'a [HashMap<String, usize>],
    pinned_indices: &'a HashMap<String, usize>,
    pinned_ptr: ir::Value,
    out_ptr: ir::Value,
    matcher: &'a Matcher,
    msg: ir::Value,
    binary_data_gvs: &'a HashMap<Vec<u8>, ir::GlobalValue>,
    matcher_eq_bytes_fref: Option<ir::FuncRef>,
    matcher_map_get_fref: Option<ir::FuncRef>,
}

#[derive(Default, Clone)]
struct MatcherEmitState {
    values: HashMap<crate::matcher::SubjectRef, ir::Value>,
}

fn finish_failed_matcher_body(b: &mut FunctionBuilder<'_>, miss_block: ir::Block) {
    let zero = b.ins().iconst(types::I32, 0);
    b.ins().return_(&[zero]);
    let to_miss = b.create_block();
    b.switch_to_block(to_miss);
    b.seal_block(to_miss);
    b.ins().jump(miss_block, &[]);
    b.switch_to_block(miss_block);
    b.seal_block(miss_block);
    let zero2 = b.ins().iconst(types::I32, 0);
    b.ins().return_(&[zero2]);
}

fn emit_matcher_node(
    b: &mut FunctionBuilder<'_>,
    ctx: &MatcherCtx<'_>,
    node_id: crate::matcher::NodeId,
    miss: ir::Block,
    state: &mut MatcherEmitState,
) -> Result<(), CodegenError> {
    let node = ctx
        .matcher
        .node(node_id)
        .ok_or_else(|| CodegenError::new(format!("matcher node {:?} out of bounds", node_id)))?;
    match node {
        MatcherNode::Fail { .. } => {
            b.ins().jump(miss, &[]);
            let dead = b.create_block();
            b.switch_to_block(dead);
            b.seal_block(dead);
            Ok(())
        }
        MatcherNode::Leaf(leaf) => {
            if leaf.guard.is_some() {
                return Err(CodegenError::new(
                    "receive ABI matcher cannot emit guarded Matcher leaf yet (fz-puj.54.12)",
                ));
            }
            let bound = &ctx.bound_indices_per_clause[leaf.body_id as usize];
            for binding in &leaf.bindings {
                let val = resolve_matcher_subject(b, ctx, &binding.source, state)?;
                if let Some(&idx) = bound.get(&binding.name) {
                    b.ins().store(
                        MemFlags::trusted(),
                        val,
                        ctx.out_ptr,
                        (idx * SLOT_BYTES as usize) as i32,
                    );
                }
            }
            let k = b.ins().iconst(types::I32, (leaf.body_id + 1) as i64);
            b.ins().return_(&[k]);
            let dead = b.create_block();
            b.switch_to_block(dead);
            b.seal_block(dead);
            Ok(())
        }
        MatcherNode::Switch {
            subject,
            kind,
            cases,
            default,
            ..
        } => {
            let val = resolve_matcher_subject(b, ctx, subject, state)?;
            for (key, case_node) in cases {
                let match_b = b.create_block();
                let next_b = b.create_block();
                emit_matcher_switch_key_test(b, ctx, val, kind, key, match_b, next_b)?;
                b.switch_to_block(match_b);
                b.seal_block(match_b);
                let mut case_state = state.clone();
                emit_matcher_node(b, ctx, *case_node, miss, &mut case_state)?;
                b.switch_to_block(next_b);
                b.seal_block(next_b);
            }
            emit_matcher_node(b, ctx, *default, miss, state)
        }
        MatcherNode::Test {
            test,
            on_true,
            on_false,
            ..
        } => {
            let true_b = b.create_block();
            let false_b = b.create_block();
            emit_matcher_test(b, ctx, test, true_b, false_b, state)?;
            b.switch_to_block(true_b);
            b.seal_block(true_b);
            let mut true_state = state.clone();
            emit_matcher_node(b, ctx, *on_true, miss, &mut true_state)?;
            b.switch_to_block(false_b);
            b.seal_block(false_b);
            emit_matcher_node(b, ctx, *on_false, miss, state)
        }
    }
}

fn resolve_matcher_subject(
    b: &mut FunctionBuilder<'_>,
    ctx: &MatcherCtx<'_>,
    sref: &crate::matcher::SubjectRef,
    state: &mut MatcherEmitState,
) -> Result<ir::Value, CodegenError> {
    if let Some(v) = state.values.get(sref).copied() {
        return Ok(v);
    }
    let v = match sref {
        crate::matcher::SubjectRef::Input(id) if id.0 == 0 => ctx.msg,
        crate::matcher::SubjectRef::Input(id) => {
            return Err(CodegenError::new(format!(
                "receive ABI matcher has no input {:?}",
                id
            )));
        }
        crate::matcher::SubjectRef::TupleField { tuple, index } => {
            let parent = resolve_matcher_subject(b, ctx, tuple, state)?;
            let off = HEADER_SIZE + (*index as i32) * SLOT_BYTES;
            b.ins().load(types::I64, MemFlags::trusted(), parent, off)
        }
        crate::matcher::SubjectRef::ListHead(list) => {
            let parent = resolve_matcher_subject(b, ctx, list, state)?;
            b.ins().load(types::I64, MemFlags::trusted(), parent, 16)
        }
        crate::matcher::SubjectRef::ListTail(list) => {
            let parent = resolve_matcher_subject(b, ctx, list, state)?;
            b.ins().load(types::I64, MemFlags::trusted(), parent, 24)
        }
        crate::matcher::SubjectRef::MapValue { map, key } => {
            let map = resolve_matcher_subject(b, ctx, map, state)?;
            emit_matcher_map_get_value(b, ctx, map, key)?
        }
        crate::matcher::SubjectRef::BitstringField { .. } => {
            return Err(CodegenError::new(
                "receive ABI matcher cannot materialize bitstring fields yet (fz-puj.50)",
            ));
        }
    };
    state.values.insert(sref.clone(), v);
    Ok(v)
}

fn emit_matcher_test(
    b: &mut FunctionBuilder<'_>,
    ctx: &MatcherCtx<'_>,
    test: &MatcherTest,
    true_b: ir::Block,
    false_b: ir::Block,
    state: &mut MatcherEmitState,
) -> Result<(), CodegenError> {
    match test {
        MatcherTest::EqConst { subject, value } => {
            let val = resolve_matcher_subject(b, ctx, subject, state)?;
            emit_matcher_const_test(b, ctx, val, value, true_b, false_b)
        }
        MatcherTest::EqPinned { subject, pinned } => {
            let val = resolve_matcher_subject(b, ctx, subject, state)?;
            let p =
                ctx.matcher.pinned.get(pinned.0 as usize).ok_or_else(|| {
                    CodegenError::new(format!("pinned {:?} out of bounds", pinned))
                })?;
            let &idx = ctx.pinned_indices.get(&p.name).ok_or_else(|| {
                CodegenError::new(format!("pinned ^{} not in matcher's pinned table", p.name))
            })?;
            let want = b.ins().load(
                types::I64,
                MemFlags::trusted(),
                ctx.pinned_ptr,
                (idx * SLOT_BYTES as usize) as i32,
            );
            let cmp = b.ins().icmp(IntCC::Equal, val, want);
            b.ins().brif(cmp, true_b, &[], false_b, &[]);
            Ok(())
        }
        MatcherTest::TupleArity { subject, arity } => {
            let val = resolve_matcher_subject(b, ctx, subject, state)?;
            emit_tuple_arity_test(
                b,
                ctx.tuple_schema_ids,
                val,
                *arity as usize,
                true_b,
                false_b,
            )
        }
        MatcherTest::ListCons { subject } => {
            let val = resolve_matcher_subject(b, ctx, subject, state)?;
            emit_list_cons_test(b, val, true_b, false_b)
        }
        MatcherTest::MapKind { subject } => {
            let val = resolve_matcher_subject(b, ctx, subject, state)?;
            emit_heap_kind_test(b, val, 7, true_b, false_b);
            Ok(())
        }
        MatcherTest::MapHasKey { subject, key } => {
            let val = resolve_matcher_subject(b, ctx, subject, state)?;
            let got = emit_matcher_map_get_value(b, ctx, val, key)?;
            let nil = b.ins().iconst(types::I64, NIL_BITS);
            let cmp = b.ins().icmp(IntCC::NotEqual, got, nil);
            b.ins().brif(cmp, true_b, &[], false_b, &[]);
            Ok(())
        }
        MatcherTest::Bitstring { .. } => Err(CodegenError::new(
            "receive ABI matcher cannot emit bitstring tests yet (fz-puj.50)",
        )),
        MatcherTest::Type { .. } => Err(CodegenError::new(
            "receive ABI matcher cannot emit type tests yet",
        )),
    }
}

fn emit_matcher_switch_key_test(
    b: &mut FunctionBuilder<'_>,
    ctx: &MatcherCtx<'_>,
    val: ir::Value,
    kind: &crate::matcher::SwitchKind,
    key: &crate::matcher::SwitchKey,
    match_b: ir::Block,
    next_b: ir::Block,
) -> Result<(), CodegenError> {
    match (kind, key) {
        (crate::matcher::SwitchKind::Atom, crate::matcher::SwitchKey::AtomName(name)) => {
            let Some(bits) =
                matcher_const_bits(ctx.fz_module, &MatcherConst::AtomName(name.clone()))?
            else {
                b.ins().jump(next_b, &[]);
                return Ok(());
            };
            br_bits_eq_to_blocks(b, val, bits, match_b, next_b);
            Ok(())
        }
        (crate::matcher::SwitchKind::Int, crate::matcher::SwitchKey::Int(n)) => {
            br_bits_eq_to_blocks(b, val, ((*n as u64) << 3) | TAG_INT as u64, match_b, next_b);
            Ok(())
        }
        (crate::matcher::SwitchKind::Bool, crate::matcher::SwitchKey::Bool(v)) => {
            let bits = if *v {
                TRUE_BITS as u64
            } else {
                fz_runtime::fz_value::FALSE_BITS
            };
            br_bits_eq_to_blocks(b, val, bits, match_b, next_b);
            Ok(())
        }
        (crate::matcher::SwitchKind::Nil, crate::matcher::SwitchKey::Nil)
        | (crate::matcher::SwitchKind::ListCons, crate::matcher::SwitchKey::Nil) => {
            br_bits_eq_to_blocks(b, val, NIL_BITS as u64, match_b, next_b);
            Ok(())
        }
        (crate::matcher::SwitchKind::TupleArity, crate::matcher::SwitchKey::Arity(arity)) => {
            emit_tuple_arity_test(
                b,
                ctx.tuple_schema_ids,
                val,
                *arity as usize,
                match_b,
                next_b,
            )
        }
        (crate::matcher::SwitchKind::ListCons, crate::matcher::SwitchKey::EmptyList) => {
            br_bits_eq_to_blocks(b, val, EMPTY_LIST_BITS as u64, match_b, next_b);
            Ok(())
        }
        (crate::matcher::SwitchKind::ListCons, crate::matcher::SwitchKey::Cons) => {
            emit_list_cons_test(b, val, match_b, next_b)
        }
        (crate::matcher::SwitchKind::Float, crate::matcher::SwitchKey::FloatBits(bits)) => {
            emit_float_literal_test(b, val, *bits, match_b, next_b)
        }
        (crate::matcher::SwitchKind::Binary, crate::matcher::SwitchKey::Utf8Binary(bytes)) => {
            emit_binary_literal_test(
                b,
                ctx.binary_data_gvs,
                ctx.matcher_eq_bytes_fref,
                val,
                bytes,
                match_b,
                next_b,
            )
        }
        _ => Err(CodegenError::new(format!(
            "Matcher Switch kind/key combination not yet supported in receive matcher: {:?} / {:?}",
            kind, key
        ))),
    }
}

fn emit_matcher_const_test(
    b: &mut FunctionBuilder<'_>,
    ctx: &MatcherCtx<'_>,
    val: ir::Value,
    value: &MatcherConst,
    match_b: ir::Block,
    next_b: ir::Block,
) -> Result<(), CodegenError> {
    match value {
        MatcherConst::FloatBits(bits) => emit_float_literal_test(b, val, *bits, match_b, next_b),
        MatcherConst::Utf8Binary(bytes) => emit_binary_literal_test(
            b,
            ctx.binary_data_gvs,
            ctx.matcher_eq_bytes_fref,
            val,
            bytes,
            match_b,
            next_b,
        ),
        MatcherConst::PreparedKey(_) => Err(CodegenError::new(
            "prepared heap map keys are not supported in receive ABI matcher yet (fz-puj.54.6)",
        )),
        other => {
            let Some(bits) = matcher_const_bits(ctx.fz_module, other)? else {
                b.ins().jump(next_b, &[]);
                return Ok(());
            };
            br_bits_eq_to_blocks(b, val, bits, match_b, next_b);
            Ok(())
        }
    }
}

fn emit_matcher_map_get_value(
    b: &mut FunctionBuilder<'_>,
    ctx: &MatcherCtx<'_>,
    map: ir::Value,
    key: &MatcherConst,
) -> Result<ir::Value, CodegenError> {
    let Some(fref) = ctx.matcher_map_get_fref else {
        return Err(CodegenError::new(
            "Map matcher test requires fz_matcher_map_get; runtime not linked in this context",
        ));
    };
    let Some(key_bits) = matcher_const_bits(ctx.fz_module, key)? else {
        return Err(CodegenError::new(format!(
            "map-pattern key {:?} cannot be materialized in receive ABI matcher",
            key
        )));
    };
    let key_v = b.ins().iconst(types::I64, key_bits as i64);
    let inst = b.ins().call(fref, &[map, key_v]);
    Ok(b.inst_results(inst)[0])
}

fn matcher_const_bits(
    fz_module: &Module,
    value: &MatcherConst,
) -> Result<Option<u64>, CodegenError> {
    Ok(match value {
        MatcherConst::Int(n) => Some(((*n as u64) << 3) | TAG_INT as u64),
        MatcherConst::AtomName(name) => fz_module
            .atom_names
            .iter()
            .position(|n| n == name)
            .map(|id| ((id as u64) << 3) | TAG_ATOM as u64),
        MatcherConst::Bool(true) => Some(TRUE_BITS as u64),
        MatcherConst::Bool(false) => Some(fz_runtime::fz_value::FALSE_BITS),
        MatcherConst::Nil => Some(NIL_BITS as u64),
        MatcherConst::EmptyList => Some(EMPTY_LIST_BITS as u64),
        MatcherConst::FloatBits(_) | MatcherConst::Utf8Binary(_) | MatcherConst::PreparedKey(_) => {
            None
        }
    })
}

fn br_bits_eq_to_blocks(
    b: &mut FunctionBuilder<'_>,
    val: ir::Value,
    bits: u64,
    match_b: ir::Block,
    next_b: ir::Block,
) {
    let want = b.ins().iconst(types::I64, bits as i64);
    let cmp = b.ins().icmp(IntCC::Equal, val, want);
    b.ins().brif(cmp, match_b, &[], next_b, &[]);
}

fn emit_heap_kind_test(
    b: &mut FunctionBuilder<'_>,
    val: ir::Value,
    kind: u16,
    match_b: ir::Block,
    next_b: ir::Block,
) {
    let tag = b.ins().band_imm(val, TAG_MASK);
    let ptr_tag = b.ins().iconst(types::I64, TAG_PTR);
    let c0 = b.create_block();
    let cmp0 = b.ins().icmp(IntCC::Equal, tag, ptr_tag);
    b.ins().brif(cmp0, c0, &[], next_b, &[]);
    b.switch_to_block(c0);
    b.seal_block(c0);

    let empty = b.ins().iconst(types::I64, EMPTY_LIST_BITS);
    let c1 = b.create_block();
    let cmp1 = b.ins().icmp(IntCC::NotEqual, val, empty);
    b.ins().brif(cmp1, c1, &[], next_b, &[]);
    b.switch_to_block(c1);
    b.seal_block(c1);

    let null = b.ins().iconst(types::I64, 0);
    let c2 = b.create_block();
    let cmp2 = b.ins().icmp(IntCC::NotEqual, val, null);
    b.ins().brif(cmp2, c2, &[], next_b, &[]);
    b.switch_to_block(c2);
    b.seal_block(c2);

    let actual = b.ins().load(types::I16, MemFlags::trusted(), val, 0);
    let want = b.ins().iconst(types::I16, kind as i64);
    let cmp3 = b.ins().icmp(IntCC::Equal, actual, want);
    b.ins().brif(cmp3, match_b, &[], next_b, &[]);
}

struct DecisionCtx<'a> {
    fz_module: &'a Module,
    tuple_schema_ids: &'a HashMap<usize, u32>,
    /// per-clause body_id → bound_name → out_ptr slot index
    bound_indices_per_clause: &'a [HashMap<String, usize>],
    /// pinned name → pinned_ptr slot index (shared across clauses)
    pinned_indices: &'a HashMap<String, usize>,
    pinned_ptr: ir::Value,
    out_ptr: ir::Value,
    clauses: &'a [ReceiveClause],
    /// Root subject Var → ir::Value (i.e. Var(0) → `msg`). Subject refs
    /// for tuple fields project from the root recursively at use time.
    root_values: &'a HashMap<Var, ir::Value>,
    /// fz-puj.45 (X4) — per-function GlobalValue for each unique binary
    /// literal byte payload referenced by any clause. Looked up by the
    /// raw bytes; the matcher emits `symbol_value` to materialise the
    /// pointer at the call site.
    binary_data_gvs: &'a HashMap<Vec<u8>, ir::GlobalValue>,
    /// fz-puj.45 (X4) — `fz_matcher_eq_bytes` per-function FuncRef. None
    /// in unit-test contexts that don't link the runtime; the binary
    /// emit path checks this and surfaces a clean CodegenError instead.
    matcher_eq_bytes_fref: Option<ir::FuncRef>,
    /// fz-puj.47 (X6) — `fz_matcher_map_get` per-function FuncRef. Same
    /// None-in-unit-tests contract as matcher_eq_bytes_fref.
    matcher_map_get_fref: Option<ir::FuncRef>,
}

/// Resolve a `SubjectRef` to a Cranelift value in the current block.
/// Always projects in the active block so dominance holds — no caching
/// across the Decision tree.
fn resolve_subject(
    b: &mut FunctionBuilder<'_>,
    ctx: &DecisionCtx,
    sref: &SubjectRef,
) -> Result<ir::Value, CodegenError> {
    match sref {
        SubjectRef::Var(v) => ctx
            .root_values
            .get(v)
            .copied()
            .ok_or_else(|| CodegenError::new(format!("unbound root subject Var({})", v.0))),
        SubjectRef::TupleField { tuple, index } => {
            let parent = resolve_subject(b, ctx, tuple)?;
            let off = HEADER_SIZE + (*index as i32) * SLOT_BYTES;
            Ok(b.ins().load(types::I64, MemFlags::trusted(), parent, off))
        }
        // fz-puj.44 (X3) — ListHead/ListTail project from the parent cons
        // cell. Header is 16 bytes; head sits at offset 16, tail at 24.
        // Mirrors ir_codegen::lower_collection_prim Prim::ListHead/Tail.
        // Callers only resolve these inside a SwitchKey::Cons arm, so the
        // parent is guaranteed (by the matrix specializer) to be a Cons.
        SubjectRef::ListHead(list) => {
            let parent = resolve_subject(b, ctx, list)?;
            Ok(b.ins().load(types::I64, MemFlags::trusted(), parent, 16))
        }
        SubjectRef::ListTail(list) => {
            let parent = resolve_subject(b, ctx, list)?;
            Ok(b.ins().load(types::I64, MemFlags::trusted(), parent, 24))
        }
    }
}

fn emit_decision(
    b: &mut FunctionBuilder<'_>,
    ctx: &DecisionCtx,
    d: &Decision,
    miss: ir::Block,
) -> Result<(), CodegenError> {
    match d {
        Decision::Fail => {
            b.ins().jump(miss, &[]);
            // Open a dead continuation so callers can keep emitting.
            let dead = b.create_block();
            b.switch_to_block(dead);
            b.seal_block(dead);
            Ok(())
        }
        Decision::Leaf {
            body_id, bindings, ..
        } => {
            // Write each bound value to out_ptr at the clause's slot index.
            let bound = &ctx.bound_indices_per_clause[*body_id as usize];
            for (name, sref) in bindings {
                let val = resolve_subject(b, ctx, sref)?;
                if let Some(&idx) = bound.get(name) {
                    b.ins().store(
                        MemFlags::trusted(),
                        val,
                        ctx.out_ptr,
                        (idx * SLOT_BYTES as usize) as i32,
                    );
                }
            }
            let k = b.ins().iconst(types::I32, (*body_id + 1) as i64);
            b.ins().return_(&[k]);
            // Dead continuation block so caller can keep emitting.
            let dead = b.create_block();
            b.switch_to_block(dead);
            b.seal_block(dead);
            Ok(())
        }
        Decision::Switch {
            subject,
            kind,
            cases,
            default,
        } => {
            let val = resolve_subject(b, ctx, subject)?;
            for (key, case_d) in cases {
                let match_b = b.create_block();
                let next_b = b.create_block();
                emit_switch_key_test(b, ctx, val, kind, key, match_b, next_b)?;
                b.switch_to_block(match_b);
                b.seal_block(match_b);
                emit_decision(b, ctx, case_d, miss)?;
                b.switch_to_block(next_b);
                b.seal_block(next_b);
            }
            emit_decision(b, ctx, default, miss)
        }
        Decision::PerRow {
            subjects,
            row,
            on_fail,
            ..
        } => {
            // Fall back to the AST-walking compile_pattern for every
            // column of the row. After tuple-arity specialization the
            // matrix may have several columns; each row.patterns[c] is
            // tested against subjects[c]. Any column miss → on_fail.
            let on_fail_block = b.create_block();
            let bound_indices: HashMap<&str, usize> = ctx.bound_indices_per_clause
                [row.body_id as usize]
                .iter()
                .map(|(n, &i)| (n.as_str(), i))
                .collect();
            let pinned_indices: HashMap<&str, usize> = ctx
                .pinned_indices
                .iter()
                .map(|(n, &i)| (n.as_str(), i))
                .collect();
            let pat_ctx = PatternCtx {
                fz_module: ctx.fz_module,
                tuple_schema_ids: ctx.tuple_schema_ids,
                bound_indices: &bound_indices,
                pinned_indices: &pinned_indices,
                pinned_ptr: ctx.pinned_ptr,
                out_ptr: ctx.out_ptr,
                binary_data_gvs: ctx.binary_data_gvs,
                matcher_eq_bytes_fref: ctx.matcher_eq_bytes_fref,
                matcher_map_get_fref: ctx.matcher_map_get_fref,
            };
            for (col_subject, col_pat) in subjects.iter().zip(&row.patterns) {
                let col_val = resolve_subject(b, ctx, col_subject)?;
                compile_pattern(b, &pat_ctx, col_val, &col_pat.node, on_fail_block)?;
            }
            // All columns matched: return clause index + 1.
            let k = b.ins().iconst(types::I32, (row.body_id + 1) as i64);
            b.ins().return_(&[k]);
            // on_fail path → next decision.
            b.switch_to_block(on_fail_block);
            b.seal_block(on_fail_block);
            emit_decision(b, ctx, on_fail, miss)
        }
    }
}

fn emit_switch_key_test(
    b: &mut FunctionBuilder<'_>,
    ctx: &DecisionCtx,
    val: ir::Value,
    kind: &SwitchKind,
    key: &SwitchKey,
    match_b: ir::Block,
    next_b: ir::Block,
) -> Result<(), CodegenError> {
    match (kind, key) {
        (SwitchKind::Atom, SwitchKey::AtomName(name)) => {
            let Some(id) = ctx
                .fz_module
                .atom_names
                .iter()
                .position(|n| n == name)
                .map(|i| i as u32)
            else {
                // Unregistered atom — no fz value can match.
                b.ins().jump(next_b, &[]);
                return Ok(());
            };
            let tagged = ((id as u64) << 3) | (TAG_ATOM as u64);
            let want = b.ins().iconst(types::I64, tagged as i64);
            let cmp = b.ins().icmp(IntCC::Equal, val, want);
            b.ins().brif(cmp, match_b, &[], next_b, &[]);
            Ok(())
        }
        (SwitchKind::Int, SwitchKey::Int(n)) => {
            let tagged = ((*n as u64) << 3) | (TAG_INT as u64);
            let want = b.ins().iconst(types::I64, tagged as i64);
            let cmp = b.ins().icmp(IntCC::Equal, val, want);
            b.ins().brif(cmp, match_b, &[], next_b, &[]);
            Ok(())
        }
        (SwitchKind::Bool, SwitchKey::Bool(true)) => {
            let want = b.ins().iconst(types::I64, TRUE_BITS);
            let cmp = b.ins().icmp(IntCC::Equal, val, want);
            b.ins().brif(cmp, match_b, &[], next_b, &[]);
            Ok(())
        }
        (SwitchKind::Bool, SwitchKey::Bool(false)) => {
            let want = b
                .ins()
                .iconst(types::I64, fz_runtime::fz_value::FALSE_BITS as i64);
            let cmp = b.ins().icmp(IntCC::Equal, val, want);
            b.ins().brif(cmp, match_b, &[], next_b, &[]);
            Ok(())
        }
        (SwitchKind::Nil, SwitchKey::Nil) => {
            let want = b.ins().iconst(types::I64, NIL_BITS);
            let cmp = b.ins().icmp(IntCC::Equal, val, want);
            b.ins().brif(cmp, match_b, &[], next_b, &[]);
            Ok(())
        }
        (SwitchKind::TupleArity, SwitchKey::Arity(arity)) => emit_tuple_arity_test(
            b,
            ctx.tuple_schema_ids,
            val,
            *arity as usize,
            match_b,
            next_b,
        ),
        // fz-puj.44 (X3) — list cons / [] / nil. SwitchKey::Nil and
        // SwitchKey::EmptyList are scalar bit-pattern checks. SwitchKey::Cons
        // verifies tag == TAG_PTR, val != EMPTY_LIST_BITS, val != 0, and
        // HeapHeader::kind == HeapKind::List (= 1). After the test, the
        // SwitchKey::Cons arm body uses SubjectRef::ListHead/ListTail to
        // project head/tail safely from the cons cell.
        (SwitchKind::ListCons, SwitchKey::Nil) => {
            let want = b.ins().iconst(types::I64, NIL_BITS);
            let cmp = b.ins().icmp(IntCC::Equal, val, want);
            b.ins().brif(cmp, match_b, &[], next_b, &[]);
            Ok(())
        }
        (SwitchKind::ListCons, SwitchKey::EmptyList) => {
            let want = b.ins().iconst(types::I64, EMPTY_LIST_BITS);
            let cmp = b.ins().icmp(IntCC::Equal, val, want);
            b.ins().brif(cmp, match_b, &[], next_b, &[]);
            Ok(())
        }
        (SwitchKind::ListCons, SwitchKey::Cons) => emit_list_cons_test(b, val, match_b, next_b),
        // fz-puj.46 (X5) — boxed float literal: tag/kind check + bit-equality
        // against the f64 payload. SwitchKey::FloatBits already carries the
        // literal's bit pattern, so the test inlines as a single icmp on
        // the loaded i64 (matches case-pattern lowering semantics —
        // structural bit-eq, NaN-distinguishing).
        (SwitchKind::Float, SwitchKey::FloatBits(bits)) => {
            emit_float_literal_test(b, val, *bits, match_b, next_b)
        }
        // fz-puj.45 (X4) — utf8 binary literal: dispatch via runtime helper.
        (SwitchKind::Binary, SwitchKey::Utf8Binary(bytes)) => emit_binary_literal_test(
            b,
            ctx.binary_data_gvs,
            ctx.matcher_eq_bytes_fref,
            val,
            bytes,
            match_b,
            next_b,
        ),
        _ => Err(CodegenError::new(format!(
            "Decision Switch kind/key combination not yet supported in receive matcher: {:?} / {:?}",
            kind, key
        ))),
    }
}

/// Chain of equality / load checks that verifies `val` is a tuple of
/// the given arity. Branches to `match_b` on success, `next_b` on any
/// mismatch. Mirrors `compile_tuple_shape` but parameterised on match
/// vs miss target blocks.
fn emit_tuple_arity_test(
    b: &mut FunctionBuilder<'_>,
    tuple_schema_ids: &HashMap<usize, u32>,
    val: ir::Value,
    arity: usize,
    match_b: ir::Block,
    next_b: ir::Block,
) -> Result<(), CodegenError> {
    let expected_schema_id = *tuple_schema_ids.get(&arity).ok_or_else(|| {
        CodegenError::new(format!(
            "matcher tuple arity {} not pre-registered (compile() walk missed it?)",
            arity
        ))
    })?;

    // tag == TAG_PTR
    let tag = b.ins().band_imm(val, TAG_MASK);
    let zero_tag = b.ins().iconst(types::I64, TAG_PTR);
    let c0 = b.create_block();
    let cmp0 = b.ins().icmp(IntCC::Equal, tag, zero_tag);
    b.ins().brif(cmp0, c0, &[], next_b, &[]);
    b.switch_to_block(c0);
    b.seal_block(c0);

    // val != EMPTY_LIST_BITS
    let empty = b.ins().iconst(types::I64, EMPTY_LIST_BITS);
    let c1 = b.create_block();
    let cmp1 = b.ins().icmp(IntCC::NotEqual, val, empty);
    b.ins().brif(cmp1, c1, &[], next_b, &[]);
    b.switch_to_block(c1);
    b.seal_block(c1);

    // val != 0
    let null = b.ins().iconst(types::I64, 0);
    let c2 = b.create_block();
    let cmp2 = b.ins().icmp(IntCC::NotEqual, val, null);
    b.ins().brif(cmp2, c2, &[], next_b, &[]);
    b.switch_to_block(c2);
    b.seal_block(c2);

    // kind == 0 (tuple)
    let kind = b.ins().load(types::I16, MemFlags::trusted(), val, 0);
    let kind_want = b.ins().iconst(types::I16, 0);
    let c3 = b.create_block();
    let cmp3 = b.ins().icmp(IntCC::Equal, kind, kind_want);
    b.ins().brif(cmp3, c3, &[], next_b, &[]);
    b.switch_to_block(c3);
    b.seal_block(c3);

    // schema == expected_schema_id
    let schema = b.ins().load(types::I32, MemFlags::trusted(), val, 8);
    let schema_want = b.ins().iconst(types::I32, expected_schema_id as i64);
    let cmp4 = b.ins().icmp(IntCC::Equal, schema, schema_want);
    b.ins().brif(cmp4, match_b, &[], next_b, &[]);
    Ok(())
}

/// fz-puj.46 (X5) — verify `val` is a HeapKind::Float boxed at `f64`
/// payload offset 16 and equal to `bits` at the bit level. Mirrors
/// emit_list_cons_test's tag/kind chain.
fn emit_float_literal_test(
    b: &mut FunctionBuilder<'_>,
    val: ir::Value,
    bits: u64,
    match_b: ir::Block,
    next_b: ir::Block,
) -> Result<(), CodegenError> {
    let tag = b.ins().band_imm(val, TAG_MASK);
    let zero_tag = b.ins().iconst(types::I64, TAG_PTR);
    let c0 = b.create_block();
    let cmp0 = b.ins().icmp(IntCC::Equal, tag, zero_tag);
    b.ins().brif(cmp0, c0, &[], next_b, &[]);
    b.switch_to_block(c0);
    b.seal_block(c0);

    let empty = b.ins().iconst(types::I64, EMPTY_LIST_BITS);
    let c1 = b.create_block();
    let cmp1 = b.ins().icmp(IntCC::NotEqual, val, empty);
    b.ins().brif(cmp1, c1, &[], next_b, &[]);
    b.switch_to_block(c1);
    b.seal_block(c1);

    let null = b.ins().iconst(types::I64, 0);
    let c2 = b.create_block();
    let cmp2 = b.ins().icmp(IntCC::NotEqual, val, null);
    b.ins().brif(cmp2, c2, &[], next_b, &[]);
    b.switch_to_block(c2);
    b.seal_block(c2);

    // HeapHeader::kind == HeapKind::Float (= 9).
    let kind = b.ins().load(types::I16, MemFlags::trusted(), val, 0);
    let kind_want = b.ins().iconst(types::I16, 9);
    let c3 = b.create_block();
    let cmp3 = b.ins().icmp(IntCC::Equal, kind, kind_want);
    b.ins().brif(cmp3, c3, &[], next_b, &[]);
    b.switch_to_block(c3);
    b.seal_block(c3);

    // Bit-compare the f64 payload at offset 16.
    let payload = b.ins().load(types::I64, MemFlags::trusted(), val, 16);
    let want = b.ins().iconst(types::I64, bits as i64);
    let cmp4 = b.ins().icmp(IntCC::Equal, payload, want);
    b.ins().brif(cmp4, match_b, &[], next_b, &[]);
    Ok(())
}

/// fz-puj.45 (X4) — walk a pattern AST and accumulate every Binary
/// literal byte payload. Duplicates are tolerated (deduped at insert).
fn collect_binary_literals_in_pattern(pat: &Pattern, out: &mut Vec<Vec<u8>>) {
    match pat {
        Pattern::Binary(bytes) => out.push(bytes.clone()),
        Pattern::As(_, inner) => collect_binary_literals_in_pattern(&inner.node, out),
        Pattern::Tuple(elems) | Pattern::List(elems, _) => {
            for e in elems {
                collect_binary_literals_in_pattern(&e.node, out);
            }
            if let Pattern::List(_, Some(tail)) = pat {
                collect_binary_literals_in_pattern(&tail.node, out);
            }
        }
        _ => {}
    }
}

fn collect_binary_literals_in_matcher(matcher: &Matcher, out: &mut Vec<Vec<u8>>) {
    for node in &matcher.nodes {
        match node {
            MatcherNode::Switch { cases, .. } => {
                for (key, _) in cases {
                    if let crate::matcher::SwitchKey::Utf8Binary(bytes) = key {
                        out.push(bytes.clone());
                    }
                }
            }
            MatcherNode::Test { test, .. } => collect_binary_literals_in_test(test, out),
            MatcherNode::Fail { .. } | MatcherNode::Leaf(_) => {}
        }
    }
}

fn collect_binary_literals_in_test(test: &MatcherTest, out: &mut Vec<Vec<u8>>) {
    match test {
        MatcherTest::EqConst {
            value: MatcherConst::Utf8Binary(bytes),
            ..
        } => out.push(bytes.clone()),
        MatcherTest::MapHasKey {
            key: MatcherConst::Utf8Binary(bytes),
            ..
        } => out.push(bytes.clone()),
        MatcherTest::Bitstring { .. }
        | MatcherTest::EqConst { .. }
        | MatcherTest::EqPinned { .. }
        | MatcherTest::TupleArity { .. }
        | MatcherTest::ListCons { .. }
        | MatcherTest::MapKind { .. }
        | MatcherTest::MapHasKey { .. }
        | MatcherTest::Type { .. } => {}
    }
}

/// fz-puj.45 (X4) — emit the call sequence that compares `val` against a
/// constant byte literal via `fz_matcher_eq_bytes`. Branches to
/// `match_b` when the helper returns 1, `next_b` when it returns 0.
/// Errors when the runtime helper isn't linked (unit-test mode).
fn emit_binary_literal_test(
    b: &mut FunctionBuilder<'_>,
    binary_data_gvs: &HashMap<Vec<u8>, ir::GlobalValue>,
    matcher_eq_bytes_fref: Option<ir::FuncRef>,
    val: ir::Value,
    bytes: &[u8],
    match_b: ir::Block,
    next_b: ir::Block,
) -> Result<(), CodegenError> {
    let Some(fref) = matcher_eq_bytes_fref else {
        return Err(CodegenError::new(
            "Pattern::Binary in receive matcher requires fz_matcher_eq_bytes; \
             runtime not linked in this context (fz-puj.45)",
        ));
    };
    let gv = binary_data_gvs.get(bytes).ok_or_else(|| {
        CodegenError::new(format!(
            "Binary literal of {} bytes missing pre-declared .data symbol (fz-puj.45)",
            bytes.len()
        ))
    })?;
    let bytes_ptr = b.ins().symbol_value(types::I64, *gv);
    let byte_len = b.ins().iconst(types::I64, bytes.len() as i64);
    let inst = b.ins().call(fref, &[val, bytes_ptr, byte_len]);
    let res = b.inst_results(inst)[0];
    let zero = b.ins().iconst(types::I32, 0);
    let cmp = b.ins().icmp(IntCC::NotEqual, res, zero);
    b.ins().brif(cmp, match_b, &[], next_b, &[]);
    Ok(())
}

/// fz-puj.44 (X3) — verify `val` is a List cons cell. Branches to
/// `match_b` only when tag == TAG_PTR, val is neither EMPTY_LIST_BITS
/// nor null, and HeapHeader::kind == HeapKind::List (= 1). On any
/// mismatch branches to `next_b`. Inside the match_b arm,
/// SubjectRef::ListHead/ListTail then project head/tail at offsets
/// 16/24 — safe because the cons-check has dominated those loads.
fn emit_list_cons_test(
    b: &mut FunctionBuilder<'_>,
    val: ir::Value,
    match_b: ir::Block,
    next_b: ir::Block,
) -> Result<(), CodegenError> {
    let tag = b.ins().band_imm(val, TAG_MASK);
    let zero_tag = b.ins().iconst(types::I64, TAG_PTR);
    let c0 = b.create_block();
    let cmp0 = b.ins().icmp(IntCC::Equal, tag, zero_tag);
    b.ins().brif(cmp0, c0, &[], next_b, &[]);
    b.switch_to_block(c0);
    b.seal_block(c0);

    let empty = b.ins().iconst(types::I64, EMPTY_LIST_BITS);
    let c1 = b.create_block();
    let cmp1 = b.ins().icmp(IntCC::NotEqual, val, empty);
    b.ins().brif(cmp1, c1, &[], next_b, &[]);
    b.switch_to_block(c1);
    b.seal_block(c1);

    let null = b.ins().iconst(types::I64, 0);
    let c2 = b.create_block();
    let cmp2 = b.ins().icmp(IntCC::NotEqual, val, null);
    b.ins().brif(cmp2, c2, &[], next_b, &[]);
    b.switch_to_block(c2);
    b.seal_block(c2);

    // HeapHeader::kind (offset 0, i16) == HeapKind::List (= 1).
    let kind = b.ins().load(types::I16, MemFlags::trusted(), val, 0);
    let kind_want = b.ins().iconst(types::I16, 1);
    let cmp3 = b.ins().icmp(IntCC::Equal, kind, kind_want);
    b.ins().brif(cmp3, match_b, &[], next_b, &[]);
    Ok(())
}

/// Per-matcher state threaded through `compile_pattern`. Borrowed for
/// the duration of one clause compilation.
struct PatternCtx<'a> {
    fz_module: &'a Module,
    tuple_schema_ids: &'a HashMap<usize, u32>,
    /// Bound name → out_ptr slot index (per-clause).
    bound_indices: &'a HashMap<&'a str, usize>,
    /// Pinned name → pinned_ptr slot index (shared across clauses).
    pinned_indices: &'a HashMap<&'a str, usize>,
    pinned_ptr: ir::Value,
    out_ptr: ir::Value,
    /// fz-puj.45 (X4) — see [`DecisionCtx::binary_data_gvs`].
    binary_data_gvs: &'a HashMap<Vec<u8>, ir::GlobalValue>,
    /// fz-puj.45 (X4) — see [`DecisionCtx::matcher_eq_bytes_fref`].
    matcher_eq_bytes_fref: Option<ir::FuncRef>,
    /// fz-puj.47 (X6) — see [`DecisionCtx::matcher_map_get_fref`].
    matcher_map_get_fref: Option<ir::FuncRef>,
}

/// Compile one pattern node into the active block. On mismatch, jumps
/// to `fail`; on match, falls through. Recurses for compound patterns.
///
/// Used by the Decision-driven matcher emitter's PerRow fallback for
/// pattern kinds the matrix can't constructor-specialize (Pinned,
/// Map, Bitstring). The top-level AST cascade was retired in fz-puj.38.
fn compile_pattern(
    b: &mut FunctionBuilder<'_>,
    ctx: &PatternCtx<'_>,
    val: ir::Value,
    pat: &Pattern,
    fail: ir::Block,
) -> Result<(), CodegenError> {
    match pat {
        Pattern::Wildcard => Ok(()),
        Pattern::Var(name) => {
            write_bound(b, ctx, name, val)?;
            Ok(())
        }
        Pattern::As(name, inner) => {
            write_bound(b, ctx, name, val)?;
            compile_pattern(b, ctx, val, &inner.node, fail)
        }
        Pattern::Pinned(name) => {
            let &idx = ctx.pinned_indices.get(name.as_str()).ok_or_else(|| {
                CodegenError::new(format!("pinned ^{} not in matcher's pinned table", name))
            })?;
            let want = b.ins().load(
                types::I64,
                MemFlags::trusted(),
                ctx.pinned_ptr,
                (idx * SLOT_BYTES as usize) as i32,
            );
            brif_neq(b, val, want, fail);
            Ok(())
        }
        Pattern::Int(n) => {
            let tagged = ((*n as u64) << 3) | (TAG_INT as u64);
            let want = b.ins().iconst(types::I64, tagged as i64);
            brif_neq(b, val, want, fail);
            Ok(())
        }
        Pattern::Bool(true) => {
            let want = b.ins().iconst(types::I64, TRUE_BITS);
            brif_neq(b, val, want, fail);
            Ok(())
        }
        Pattern::Bool(false) => {
            // fz-yan.1 — `false` is the atom with reserved id 2.
            let want = b
                .ins()
                .iconst(types::I64, fz_runtime::fz_value::FALSE_BITS as i64);
            brif_neq(b, val, want, fail);
            Ok(())
        }
        Pattern::Nil => {
            let want = b.ins().iconst(types::I64, NIL_BITS);
            brif_neq(b, val, want, fail);
            Ok(())
        }
        Pattern::Atom(name) => {
            // Unregistered atom name → no fz value can ever match.
            // Emit unconditional branch to fail.
            let Some(id) = ctx
                .fz_module
                .atom_names
                .iter()
                .position(|n| n == name)
                .map(|i| i as u32)
            else {
                b.ins().jump(fail, &[]);
                // Open an unreachable continuation block so callers can
                // still emit subsequent code without verifier errors.
                let dead = b.create_block();
                b.switch_to_block(dead);
                b.seal_block(dead);
                return Ok(());
            };
            let tagged = ((id as u64) << 3) | (TAG_ATOM as u64);
            let want = b.ins().iconst(types::I64, tagged as i64);
            brif_neq(b, val, want, fail);
            Ok(())
        }
        Pattern::Tuple(elems) => {
            compile_tuple_shape(b, ctx.tuple_schema_ids, val, elems.len(), fail)?;
            compile_tuple_fields(b, ctx, val, elems, fail)
        }
        // fz-puj.44 (X3) — list literal pattern: handle `[]`, `nil`, and
        // cons-form. The matrix specializer usually splits these into
        // Switch{ListCons}, but a List pattern can still reach PerRow if
        // a sibling row drives a different column kind. Parity with
        // ir_interp::try_match_pattern Pattern::List.
        Pattern::List(elems, tail) => {
            compile_list_pattern(b, ctx, val, elems, tail.as_deref(), fail)
        }
        // fz-puj.45 (X4) — binary literal: emit the same helper-call
        // sequence we use in Switch, branching to `fail` on mismatch.
        Pattern::Binary(bytes) => {
            let cont = b.create_block();
            emit_binary_literal_test(
                b,
                ctx.binary_data_gvs,
                ctx.matcher_eq_bytes_fref,
                val,
                bytes,
                cont,
                fail,
            )?;
            b.switch_to_block(cont);
            b.seal_block(cont);
            Ok(())
        }
        // fz-puj.46 (X5) — boxed float literal in PerRow fallback. Uses
        // the same tag/kind/payload sequence as the Switch arm above.
        Pattern::Float(f) => {
            let cont = b.create_block();
            emit_float_literal_test(b, val, f.to_bits(), cont, fail)?;
            b.switch_to_block(cont);
            b.seal_block(cont);
            Ok(())
        }
        // fz-puj.47 (X6) — map pattern via fz_matcher_map_get. Iterate
        // entries; for each: encode the key as a scalar i64 const (only
        // Atom/Int/Bool/Nil keys are supported in the matcher — Float
        // and Binary keys would need a heap object on the RHS, which
        // would require a per-receive startup allocation pass; left to
        // a follow-up if needed). Call the helper; on a NIL_BITS result
        // jump to `fail`; otherwise recurse compile_pattern on the
        // value pattern against the lookup result.
        Pattern::Map(entries) => compile_map_pattern(b, ctx, val, entries, fail),
        // Bitstring: substantial work (inline bit reader). Defer.
        Pattern::Bitstring(_) => {
            b.ins().jump(fail, &[]);
            let dead = b.create_block();
            b.switch_to_block(dead);
            b.seal_block(dead);
            Ok(())
        }
    }
}

/// fz-puj.47 (X6) — compile a `Pattern::Map(entries)` in PerRow
/// fallback. For each entry: encode the key as a scalar i64, call
/// `fz_matcher_map_get(val, key)`, branch to `fail` if the result is
/// NIL_BITS (key absent), otherwise recurse on the value pattern
/// against the lookup result. Map values that are themselves nil are
/// degenerate per the helper's contract (documented there).
fn compile_map_pattern(
    b: &mut FunctionBuilder<'_>,
    ctx: &PatternCtx<'_>,
    val: ir::Value,
    entries: &[(crate::ast::Spanned<Pattern>, crate::ast::Spanned<Pattern>)],
    fail: ir::Block,
) -> Result<(), CodegenError> {
    let Some(fref) = ctx.matcher_map_get_fref else {
        return Err(CodegenError::new(
            "Pattern::Map in receive matcher requires fz_matcher_map_get; \
             runtime not linked in this context (fz-puj.47)",
        ));
    };
    for (key_pat, val_pat) in entries {
        let key_bits = encode_scalar_key(ctx.fz_module, &key_pat.node)?;
        let key_v = b.ins().iconst(types::I64, key_bits as i64);
        let inst = b.ins().call(fref, &[val, key_v]);
        let res = b.inst_results(inst)[0];
        // Miss → NIL_BITS. Branch to fail.
        let nil = b.ins().iconst(types::I64, NIL_BITS);
        brif_eq(b, res, nil, fail);
        compile_pattern(b, ctx, res, &val_pat.node, fail)?;
    }
    Ok(())
}

/// fz-puj.47 (X6) — encode a constant-shaped map-key pattern as raw
/// FzValue bits (scalar tags only: Atom, Int, Bool, Nil). Heap-typed
/// keys (Float, Binary) require an allocated RHS the matcher can't
/// produce; those cases surface a clean CodegenError pointing at the
/// follow-up.
fn encode_scalar_key(fz_module: &Module, key: &Pattern) -> Result<u64, CodegenError> {
    match key {
        Pattern::Int(n) => Ok(((*n as u64) << 3) | TAG_INT as u64),
        Pattern::Bool(true) => Ok(TRUE_BITS as u64),
        Pattern::Bool(false) => Ok(fz_runtime::fz_value::FALSE_BITS),
        Pattern::Nil => Ok(NIL_BITS as u64),
        Pattern::Atom(name) => {
            let id = fz_module
                .atom_names
                .iter()
                .position(|n| n == name)
                .ok_or_else(|| {
                    CodegenError::new(format!(
                        "map-pattern atom key :{} not registered in module (fz-puj.47)",
                        name
                    ))
                })? as u64;
            Ok((id << 3) | TAG_ATOM as u64)
        }
        Pattern::Float(_) => Err(CodegenError::new(
            "Float map-pattern keys not yet supported in receive matcher (fz-puj.47)",
        )),
        Pattern::Binary(_) => Err(CodegenError::new(
            "Binary map-pattern keys not yet supported in receive matcher (fz-puj.47)",
        )),
        other => Err(CodegenError::new(format!(
            "non-literal map-pattern key {:?} not supported in receive matcher (fz-puj.47)",
            other
        ))),
    }
}

/// fz-puj.44 (X3) — compile a `Pattern::List(elems, tail)` in PerRow
/// fallback. Three shapes:
///   - `[]` / `[| _]` with `elems.is_empty()` && `tail.is_none()`: must
///     equal EMPTY_LIST_BITS.
///   - cons-form `[h, ...rest | tail]`: must be a HeapKind::List cell;
///     recurse: first elem against head, then either the next list
///     shape (more elems) or the tail pattern (last elem).
fn compile_list_pattern(
    b: &mut FunctionBuilder<'_>,
    ctx: &PatternCtx<'_>,
    val: ir::Value,
    elems: &[crate::ast::Spanned<Pattern>],
    tail: Option<&crate::ast::Spanned<Pattern>>,
    fail: ir::Block,
) -> Result<(), CodegenError> {
    if elems.is_empty() {
        if tail.is_some() {
            // Parser-disallowed shape; treat as no match.
            b.ins().jump(fail, &[]);
            let dead = b.create_block();
            b.switch_to_block(dead);
            b.seal_block(dead);
            return Ok(());
        }
        // `[]` — must equal EMPTY_LIST_BITS.
        let want = b.ins().iconst(types::I64, EMPTY_LIST_BITS);
        brif_neq(b, val, want, fail);
        return Ok(());
    }
    // Verify val is a HeapKind::List cell.
    let tag = b.ins().band_imm(val, TAG_MASK);
    let zero_tag = b.ins().iconst(types::I64, TAG_PTR);
    brif_neq(b, tag, zero_tag, fail);
    let empty = b.ins().iconst(types::I64, EMPTY_LIST_BITS);
    brif_eq(b, val, empty, fail);
    let null = b.ins().iconst(types::I64, 0);
    brif_eq(b, val, null, fail);
    let kind = b.ins().load(types::I16, MemFlags::trusted(), val, 0);
    let kind_want = b.ins().iconst(types::I16, 1);
    brif_neq_typed(b, kind, kind_want, fail, types::I16);
    // Recurse: head pattern against offset 16, then either next-elems list
    // or tail pattern against offset 24.
    let head_val = b.ins().load(types::I64, MemFlags::trusted(), val, 16);
    compile_pattern(b, ctx, head_val, &elems[0].node, fail)?;
    let tail_val = b.ins().load(types::I64, MemFlags::trusted(), val, 24);
    if elems.len() == 1 {
        match tail {
            Some(t) => compile_pattern(b, ctx, tail_val, &t.node, fail),
            None => {
                // Implicit empty-list tail.
                let want = b.ins().iconst(types::I64, EMPTY_LIST_BITS);
                brif_neq(b, tail_val, want, fail);
                Ok(())
            }
        }
    } else {
        compile_list_pattern(b, ctx, tail_val, &elems[1..], tail, fail)
    }
}

fn compile_tuple_shape(
    b: &mut FunctionBuilder<'_>,
    tuple_schema_ids: &HashMap<usize, u32>,
    val: ir::Value,
    arity: usize,
    fail: ir::Block,
) -> Result<(), CodegenError> {
    let expected_schema_id = *tuple_schema_ids.get(&arity).ok_or_else(|| {
        CodegenError::new(format!(
            "matcher tuple arity {} not pre-registered (compile() walk missed it?)",
            arity
        ))
    })?;

    let tag = b.ins().band_imm(val, TAG_MASK);
    let zero_tag = b.ins().iconst(types::I64, TAG_PTR);
    brif_neq(b, tag, zero_tag, fail);
    let empty = b.ins().iconst(types::I64, EMPTY_LIST_BITS);
    brif_eq(b, val, empty, fail);
    let null = b.ins().iconst(types::I64, 0);
    brif_eq(b, val, null, fail);
    let kind = b.ins().load(types::I16, MemFlags::trusted(), val, 0);
    let kind_want = b.ins().iconst(types::I16, 0);
    brif_neq_typed(b, kind, kind_want, fail, types::I16);
    let schema = b.ins().load(types::I32, MemFlags::trusted(), val, 8);
    let schema_want = b.ins().iconst(types::I32, expected_schema_id as i64);
    brif_neq_typed(b, schema, schema_want, fail, types::I32);
    Ok(())
}

fn compile_tuple_fields(
    b: &mut FunctionBuilder<'_>,
    ctx: &PatternCtx<'_>,
    val: ir::Value,
    elems: &[crate::ast::Spanned<Pattern>],
    fail: ir::Block,
) -> Result<(), CodegenError> {
    for (i, e) in elems.iter().enumerate() {
        let off = HEADER_SIZE + (i as i32) * SLOT_BYTES;
        let field = b.ins().load(types::I64, MemFlags::trusted(), val, off);
        compile_pattern(b, ctx, field, &e.node, fail)?;
    }
    Ok(())
}

fn write_bound(
    b: &mut FunctionBuilder<'_>,
    ctx: &PatternCtx<'_>,
    name: &str,
    val: ir::Value,
) -> Result<(), CodegenError> {
    let &idx = ctx.bound_indices.get(name).ok_or_else(|| {
        CodegenError::new(format!(
            "bound `{}` not in clause's bound_names table",
            name
        ))
    })?;
    b.ins().store(
        MemFlags::trusted(),
        val,
        ctx.out_ptr,
        (idx * SLOT_BYTES as usize) as i32,
    );
    Ok(())
}

/// Branch to `fail` if `lhs != rhs` (i64). Continues in a fresh
/// fall-through block so caller can keep emitting linearly.
fn brif_neq(b: &mut FunctionBuilder<'_>, lhs: ir::Value, rhs: ir::Value, fail: ir::Block) {
    let cmp = b.ins().icmp(IntCC::NotEqual, lhs, rhs);
    let cont = b.create_block();
    b.ins().brif(cmp, fail, &[], cont, &[]);
    b.switch_to_block(cont);
    b.seal_block(cont);
}

fn brif_eq(b: &mut FunctionBuilder<'_>, lhs: ir::Value, rhs: ir::Value, fail: ir::Block) {
    let cmp = b.ins().icmp(IntCC::Equal, lhs, rhs);
    let cont = b.create_block();
    b.ins().brif(cmp, fail, &[], cont, &[]);
    b.switch_to_block(cont);
    b.seal_block(cont);
}

fn brif_neq_typed(
    b: &mut FunctionBuilder<'_>,
    lhs: ir::Value,
    rhs: ir::Value,
    fail: ir::Block,
    _ty: ir::Type,
) {
    let cmp = b.ins().icmp(IntCC::NotEqual, lhs, rhs);
    let cont = b.create_block();
    b.ins().brif(cmp, fail, &[], cont, &[]);
    b.switch_to_block(cont);
    b.seal_block(cont);
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::{Pattern as AstPattern, Spanned};
    use crate::diag::Span;
    use crate::fz_ir::{FnId, ReceiveClause, Var};
    use cranelift_codegen::settings::{self, Configurable};
    use cranelift_jit::{JITBuilder, JITModule};

    fn make_jit() -> (JITModule, FunctionBuilderContext) {
        let isa_builder = cranelift_native::builder().expect("native isa");
        let mut flag_builder = settings::builder();
        flag_builder.set("opt_level", "none").unwrap();
        flag_builder.set("is_pic", "false").unwrap();
        let isa = isa_builder
            .finish(settings::Flags::new(flag_builder))
            .expect("isa finish");
        let builder = JITBuilder::with_isa(isa, cranelift_module::default_libcall_names());
        let jmod = JITModule::new(builder);
        (jmod, FunctionBuilderContext::new())
    }

    type MatcherAbi = extern "C" fn(u64, *const u64, *mut u64) -> u32;

    fn empty_module() -> Module {
        let mut m = Module::default();
        // Reserved atom IDs (fz-yan.1): nil=0, true=1, false=2.
        m.atom_names.push("nil".into());
        m.atom_names.push("true".into());
        m.atom_names.push("false".into());
        m
    }

    fn sp<T>(node: T) -> Spanned<T> {
        Spanned::dummy(node)
    }

    fn clause_with(pattern: AstPattern, bound_names: Vec<String>) -> ReceiveClause {
        ReceiveClause {
            pattern: sp(pattern),
            bound_names,
            guard: None,
            body: FnId(0),
            span: Span::DUMMY,
        }
    }

    fn finalize_and_get(mut jmod: JITModule, fid: FuncId) -> MatcherAbi {
        jmod.finalize_definitions().expect("finalize");
        let addr = jmod.get_finalized_function(fid);
        // Leak the JIT module so the code stays mapped for the test's
        // direct fn-pointer call. Tests run in their own process.
        Box::leak(Box::new(jmod));
        unsafe { std::mem::transmute(addr) }
    }

    /// Wildcard pattern: matcher returns 1 for any input.
    #[test]
    fn matcher_wildcard_matches_anything() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![clause_with(AstPattern::Wildcard, vec![])];
        let fid = declare_matcher(&mut jmod, "matcher_wildcard").unwrap();
        emit_matcher_body_from_decision(
            &mut jmod, &mut fbctx, fid, &m, &tuple_ids, &pinned, &clauses, None, None,
        )
        .unwrap();
        let f = finalize_and_get(jmod, fid);
        let mut out = [0u64; 0];
        let pin: [u64; 0] = [];
        assert_eq!(f(0xdead_beef, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(f(0, pin.as_ptr(), out.as_mut_ptr()), 1);
    }

    /// `Pattern::Int(42)`: hit returns 1 only for tagged 42.
    #[test]
    fn matcher_int_literal_hits_only_exact_tagged_value() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![clause_with(AstPattern::Int(42), vec![])];
        let fid = declare_matcher(&mut jmod, "matcher_int_42").unwrap();
        emit_matcher_body_from_decision(
            &mut jmod, &mut fbctx, fid, &m, &tuple_ids, &pinned, &clauses, None, None,
        )
        .unwrap();
        let f = finalize_and_get(jmod, fid);
        let pin: [u64; 0] = [];
        let mut out = [0u64; 0];
        let tagged_42: u64 = (42u64 << 3) | (TAG_INT as u64);
        let tagged_41: u64 = (41u64 << 3) | (TAG_INT as u64);
        assert_eq!(f(tagged_42, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(f(tagged_41, pin.as_ptr(), out.as_mut_ptr()), 0);
        assert_eq!(f(0, pin.as_ptr(), out.as_mut_ptr()), 0);
    }

    /// `Pattern::Var(name)`: any input matches, value written to out[0].
    #[test]
    fn matcher_var_pattern_writes_input_to_out_slot_zero() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![clause_with(AstPattern::Var("x".into()), vec!["x".into()])];
        let fid = declare_matcher(&mut jmod, "matcher_var_x").unwrap();
        emit_matcher_body_from_decision(
            &mut jmod, &mut fbctx, fid, &m, &tuple_ids, &pinned, &clauses, None, None,
        )
        .unwrap();
        let f = finalize_and_get(jmod, fid);
        let pin: [u64; 0] = [];
        let mut out = [0u64; 1];
        let v: u64 = 0xc0ffee;
        assert_eq!(f(v, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(out[0], v);
    }

    /// Pinned: matches only when the input matches `pinned[0]`.
    #[test]
    fn matcher_pinned_pattern_compares_against_pinned_slot() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned = vec![("p".to_string(), Var(0))];
        let clauses = vec![clause_with(AstPattern::Pinned("p".into()), vec![])];
        let fid = declare_matcher(&mut jmod, "matcher_pinned_p").unwrap();
        emit_matcher_body_from_decision(
            &mut jmod, &mut fbctx, fid, &m, &tuple_ids, &pinned, &clauses, None, None,
        )
        .unwrap();
        let f = finalize_and_get(jmod, fid);
        let mut out = [0u64; 0];
        let pin = [0x1234_5678u64];
        assert_eq!(f(0x1234_5678, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(f(0x1234_0000, pin.as_ptr(), out.as_mut_ptr()), 0);
    }

    /// Atom: registered atom hits when bits match; unregistered name
    /// emits an always-fail arm (no fz value can match).
    #[test]
    fn matcher_atom_pattern_uses_registered_atom_id() {
        let (mut jmod, mut fbctx) = make_jit();
        let mut m = empty_module();
        m.atom_names.push("k_a".into()); // id 3
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![clause_with(AstPattern::Atom("k_a".into()), vec![])];
        let fid = declare_matcher(&mut jmod, "matcher_atom_k_a").unwrap();
        emit_matcher_body_from_decision(
            &mut jmod, &mut fbctx, fid, &m, &tuple_ids, &pinned, &clauses, None, None,
        )
        .unwrap();
        let f = finalize_and_get(jmod, fid);
        let pin: [u64; 0] = [];
        let mut out = [0u64; 0];
        let tagged_k_a: u64 = (3u64 << 3) | (TAG_ATOM as u64);
        let tagged_other: u64 = (99u64 << 3) | (TAG_ATOM as u64);
        assert_eq!(f(tagged_k_a, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(f(tagged_other, pin.as_ptr(), out.as_mut_ptr()), 0);
    }

    /// Multi-clause: first-matching wins; later clauses don't run.
    #[test]
    fn matcher_first_matching_clause_wins() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![
            clause_with(AstPattern::Int(1), vec![]),
            clause_with(AstPattern::Int(2), vec![]),
            clause_with(AstPattern::Wildcard, vec![]),
        ];
        let fid = declare_matcher(&mut jmod, "matcher_multi").unwrap();
        emit_matcher_body_from_decision(
            &mut jmod, &mut fbctx, fid, &m, &tuple_ids, &pinned, &clauses, None, None,
        )
        .unwrap();
        let f = finalize_and_get(jmod, fid);
        let pin: [u64; 0] = [];
        let mut out = [0u64; 0];
        let t1: u64 = (1u64 << 3) | (TAG_INT as u64);
        let t2: u64 = (2u64 << 3) | (TAG_INT as u64);
        let t99: u64 = (99u64 << 3) | (TAG_INT as u64);
        assert_eq!(f(t1, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(f(t2, pin.as_ptr(), out.as_mut_ptr()), 2);
        assert_eq!(f(t99, pin.as_ptr(), out.as_mut_ptr()), 3);
    }

    /// Tuple `{:reply, ^ref, v}`: schema check + atom + pinned + var
    /// — the shape that the fz-recv fixture's clause exercises.
    #[test]
    fn matcher_tuple_with_atom_pinned_var_matches_arrived_message() {
        use fz_runtime::fz_value::{HeapHeader, HeapKind};

        let (mut jmod, mut fbctx) = make_jit();
        let mut m = empty_module();
        m.atom_names.push("reply".into()); // id 3

        let mut tuple_ids = HashMap::new();
        tuple_ids.insert(3, 7u32); // arity 3 → schema id 7 (test-local)

        let pinned = vec![("ref".to_string(), Var(0))];
        let pat = AstPattern::Tuple(vec![
            sp(AstPattern::Atom("reply".into())),
            sp(AstPattern::Pinned("ref".into())),
            sp(AstPattern::Var("v".into())),
        ]);
        let clauses = vec![clause_with(pat, vec!["v".into()])];
        let fid = declare_matcher(&mut jmod, "matcher_tuple_reply").unwrap();
        emit_matcher_body_from_decision(
            &mut jmod, &mut fbctx, fid, &m, &tuple_ids, &pinned, &clauses, None, None,
        )
        .unwrap();
        let f = finalize_and_get(jmod, fid);

        // Build a heap-shaped tuple: HeapHeader (16 bytes) + 3 FzValue slots.
        // 5 u64 slots = 40 bytes, 16-byte aligned via Box<[u64; 8]>.
        let mut buf: Box<[u64; 8]> = Box::new([0u64; 8]);
        let base = buf.as_mut_ptr() as *mut u8;
        // SAFETY: buf is owned for the duration of the test; we hand
        // the JIT'd matcher a pointer that's valid for read-only access.
        unsafe {
            let header = HeapHeader {
                kind: HeapKind::Struct as u16,
                flags: 0,
                size_bytes: 16 + 24,
                schema_id: 7,
                _reserved: 0,
            };
            std::ptr::write(base as *mut HeapHeader, header);
            // Fields: :reply atom (id 3), pinned value 0xaa, payload 0xbb.
            let reply_bits: u64 = (3u64 << 3) | (TAG_ATOM as u64);
            let pin_bits: u64 = 0xaa;
            let payload_bits: u64 = 0xbb;
            std::ptr::write(base.add(16) as *mut u64, reply_bits);
            std::ptr::write(base.add(24) as *mut u64, pin_bits);
            std::ptr::write(base.add(32) as *mut u64, payload_bits);
        }

        let pin = [0xaau64];
        let mut out = [0u64; 1];
        let val = base as u64; // TAG_PTR = 0; pointer is 16-byte aligned.
        assert_eq!(f(val, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(out[0], 0xbb);

        // Pinned mismatch: same tuple but pinned[0] != msg.field[1].
        let pin_other = [0xffu64];
        let mut out2 = [0u64; 1];
        assert_eq!(f(val, pin_other.as_ptr(), out2.as_mut_ptr()), 0);
    }

    /// Guards aren't supported in this ticket; explicit error keeps the
    /// boundary visible (no silent acceptance).
    #[test]
    fn matcher_rejects_clauses_with_guards() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let mut c = clause_with(AstPattern::Wildcard, vec![]);
        c.guard = Some(FnId(99));
        let clauses = vec![c];
        let fid = declare_matcher(&mut jmod, "matcher_with_guard").unwrap();
        let err = emit_matcher_body_from_decision(
            &mut jmod, &mut fbctx, fid, &m, &tuple_ids, &pinned, &clauses, None, None,
        )
        .unwrap_err();
        assert!(
            err.to_string().contains("fz-puj.42"),
            "error message points at the pure-guard ticket: {}",
            err
        );
    }

    // -----------------------------------------------------------------
    // fz-puj.20 (H9 / E2) — Decision-driven matcher emitter tests.
    //
    // Behavioral parity with `emit_matcher_body` for the H9 subset:
    // wildcard / var / as / pinned / atom / int / bool / nil / tuple.
    // -----------------------------------------------------------------

    fn build_decision_matcher(
        jmod: &mut JITModule,
        fbctx: &mut FunctionBuilderContext,
        fz_module: &Module,
        tuple_schemas: &HashMap<usize, u32>,
        pinned: &[(String, Var)],
        clauses: &[ReceiveClause],
        name: &str,
    ) -> MatcherAbi {
        let fid = declare_matcher(jmod, name).expect("declare matcher");
        emit_matcher_body_from_decision(
            jmod,
            fbctx,
            fid,
            fz_module,
            tuple_schemas,
            pinned,
            clauses,
            None,
            None,
        )
        .expect("emit decision matcher");
        finalize_and_get(std::mem::replace(jmod, make_jit().0), fid)
    }

    fn build_cached_matcher(
        jmod: &mut JITModule,
        fbctx: &mut FunctionBuilderContext,
        fz_module: &Module,
        tuple_schemas: &HashMap<usize, u32>,
        pinned: &[(String, Var)],
        clauses: &[ReceiveClause],
        name: &str,
    ) -> MatcherAbi {
        let matrix = crate::pattern_matrix::Matrix {
            subjects: vec![Var(0)],
            rows: clauses
                .iter()
                .enumerate()
                .map(|(i, c)| crate::pattern_matrix::Row {
                    patterns: vec![c.pattern.clone()],
                    preconditions: Vec::new(),
                    guard: None,
                    body_id: i as crate::pattern_matrix::BodyId,
                })
                .collect(),
        };
        let matcher =
            crate::pattern_matrix::compile_matcher_subset(matrix).expect("compile cached matcher");
        let fid = declare_matcher(jmod, name).expect("declare matcher");
        emit_matcher_body_from_matcher(
            jmod,
            fbctx,
            fid,
            fz_module,
            tuple_schemas,
            pinned,
            clauses,
            &matcher,
            None,
            None,
        )
        .expect("emit cached matcher");
        finalize_and_get(std::mem::replace(jmod, make_jit().0), fid)
    }

    #[test]
    fn cached_matcher_int_literal_hits_only_exact_tagged_value() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![clause_with(AstPattern::Int(42), vec![])];
        let f = build_cached_matcher(
            &mut jmod,
            &mut fbctx,
            &m,
            &tuple_ids,
            &pinned,
            &clauses,
            "cached_matcher_int_42",
        );
        let pin: [u64; 0] = [];
        let mut out = [0u64; 0];
        let tagged_42: u64 = (42u64 << 3) | (TAG_INT as u64);
        let tagged_41: u64 = (41u64 << 3) | (TAG_INT as u64);
        assert_eq!(f(tagged_42, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(f(tagged_41, pin.as_ptr(), out.as_mut_ptr()), 0);
    }

    #[test]
    fn decision_matcher_wildcard_matches_anything() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![clause_with(AstPattern::Wildcard, vec![])];
        let f = build_decision_matcher(
            &mut jmod,
            &mut fbctx,
            &m,
            &tuple_ids,
            &pinned,
            &clauses,
            "dm_wildcard",
        );
        let pin: [u64; 0] = [];
        let mut out = [0u64; 0];
        assert_eq!(f(0xdead_beef, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(f(0, pin.as_ptr(), out.as_mut_ptr()), 1);
    }

    #[test]
    fn decision_matcher_int_literal_hits_only_exact_tagged_value() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![clause_with(AstPattern::Int(42), vec![])];
        let f = build_decision_matcher(
            &mut jmod, &mut fbctx, &m, &tuple_ids, &pinned, &clauses, "dm_int42",
        );
        let pin: [u64; 0] = [];
        let mut out = [0u64; 0];
        let tagged_42 = ((42u64) << 3) | (TAG_INT as u64);
        let tagged_41 = ((41u64) << 3) | (TAG_INT as u64);
        assert_eq!(f(tagged_42, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(f(tagged_41, pin.as_ptr(), out.as_mut_ptr()), 0);
    }

    #[test]
    fn decision_matcher_var_writes_input_to_out_slot_zero() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![clause_with(AstPattern::Var("x".into()), vec!["x".into()])];
        let f = build_decision_matcher(
            &mut jmod, &mut fbctx, &m, &tuple_ids, &pinned, &clauses, "dm_var",
        );
        let pin: [u64; 0] = [];
        let mut out = [0u64; 1];
        let msg = ((7u64) << 3) | (TAG_INT as u64);
        assert_eq!(f(msg, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(out[0], msg);
    }

    #[test]
    fn decision_matcher_pinned_pattern_compares_against_pinned_slot() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned = vec![("p".to_string(), Var(0))];
        let clauses = vec![clause_with(AstPattern::Pinned("p".into()), vec![])];
        let f = build_decision_matcher(
            &mut jmod,
            &mut fbctx,
            &m,
            &tuple_ids,
            &pinned,
            &clauses,
            "dm_pinned",
        );
        let want = ((9u64) << 3) | (TAG_INT as u64);
        let pin = [want];
        let mut out = [0u64; 0];
        assert_eq!(f(want, pin.as_ptr(), out.as_mut_ptr()), 1);
        let other = ((10u64) << 3) | (TAG_INT as u64);
        assert_eq!(f(other, pin.as_ptr(), out.as_mut_ptr()), 0);
    }

    #[test]
    fn decision_matcher_atom_pattern_uses_registered_atom_id() {
        let (mut jmod, mut fbctx) = make_jit();
        let mut m = empty_module();
        m.atom_names.push("ping".into()); // id 3
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![clause_with(AstPattern::Atom("ping".into()), vec![])];
        let f = build_decision_matcher(
            &mut jmod, &mut fbctx, &m, &tuple_ids, &pinned, &clauses, "dm_atom",
        );
        let pin: [u64; 0] = [];
        let mut out = [0u64; 0];
        let ping_bits = ((3u64) << 3) | (TAG_ATOM as u64);
        assert_eq!(f(ping_bits, pin.as_ptr(), out.as_mut_ptr()), 1);
        let other_bits = ((99u64) << 3) | (TAG_ATOM as u64);
        assert_eq!(f(other_bits, pin.as_ptr(), out.as_mut_ptr()), 0);
    }

    #[test]
    fn decision_matcher_first_matching_clause_wins() {
        let (mut jmod, mut fbctx) = make_jit();
        let mut m = empty_module();
        m.atom_names.push("a".into()); // id 3
        m.atom_names.push("b".into()); // id 4
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![
            clause_with(AstPattern::Atom("a".into()), vec![]),
            clause_with(AstPattern::Atom("b".into()), vec![]),
            clause_with(AstPattern::Wildcard, vec![]),
        ];
        let f = build_decision_matcher(
            &mut jmod,
            &mut fbctx,
            &m,
            &tuple_ids,
            &pinned,
            &clauses,
            "dm_first_match",
        );
        let pin: [u64; 0] = [];
        let mut out = [0u64; 0];
        let a_bits = ((3u64) << 3) | (TAG_ATOM as u64);
        let b_bits = ((4u64) << 3) | (TAG_ATOM as u64);
        let other = ((5u64) << 3) | (TAG_ATOM as u64);
        assert_eq!(f(a_bits, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(f(b_bits, pin.as_ptr(), out.as_mut_ptr()), 2);
        assert_eq!(f(other, pin.as_ptr(), out.as_mut_ptr()), 3);
    }

    #[test]
    fn decision_matcher_rejects_clauses_with_guards() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let mut c = clause_with(AstPattern::Wildcard, vec![]);
        c.guard = Some(FnId(99));
        let clauses = vec![c];
        let fid = declare_matcher(&mut jmod, "dm_guarded").unwrap();
        let err = emit_matcher_body_from_decision(
            &mut jmod, &mut fbctx, fid, &m, &tuple_ids, &pinned, &clauses, None, None,
        )
        .unwrap_err();
        assert!(
            err.to_string().contains("fz-puj.42"),
            "error message points at pure-guard ticket: {}",
            err
        );
    }

    // -----------------------------------------------------------------
    // fz-puj.44 (X3) — list patterns: `[]`, `nil`, and `[h | t]`.
    // -----------------------------------------------------------------

    fn alloc_test_cons(head: u64, tail: u64) -> u64 {
        use fz_runtime::fz_value::{FzValue, alloc_list_cons};
        let p = alloc_list_cons(FzValue(head), FzValue(tail));
        p as u64 // TAG_PTR = 0
    }

    #[test]
    fn decision_matcher_nil_pattern_matches_only_nil_atom() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![clause_with(AstPattern::Nil, vec![])];
        let f = build_decision_matcher(
            &mut jmod, &mut fbctx, &m, &tuple_ids, &pinned, &clauses, "dm_nil",
        );
        let pin: [u64; 0] = [];
        let mut out = [0u64; 0];
        assert_eq!(f(NIL_BITS as u64, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(f(EMPTY_LIST_BITS as u64, pin.as_ptr(), out.as_mut_ptr()), 0);
        let other = ((7u64) << 3) | (TAG_INT as u64);
        assert_eq!(f(other, pin.as_ptr(), out.as_mut_ptr()), 0);
    }

    #[test]
    fn decision_matcher_empty_list_pattern_matches_only_empty_list() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        // `[]` literal — a List pattern with no elems and no tail.
        let clauses = vec![clause_with(AstPattern::List(vec![], None), vec![])];
        let f = build_decision_matcher(
            &mut jmod,
            &mut fbctx,
            &m,
            &tuple_ids,
            &pinned,
            &clauses,
            "dm_empty_list",
        );
        let pin: [u64; 0] = [];
        let mut out = [0u64; 0];
        assert_eq!(f(EMPTY_LIST_BITS as u64, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(f(NIL_BITS as u64, pin.as_ptr(), out.as_mut_ptr()), 0);
    }

    #[test]
    fn decision_matcher_cons_pattern_binds_head_and_tail() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        // `[h | t] -> ...`
        let pat = AstPattern::List(
            vec![sp(AstPattern::Var("h".into()))],
            Some(Box::new(sp(AstPattern::Var("t".into())))),
        );
        let clauses = vec![clause_with(pat, vec!["h".into(), "t".into()])];
        let f = build_decision_matcher(
            &mut jmod, &mut fbctx, &m, &tuple_ids, &pinned, &clauses, "dm_cons",
        );
        let pin: [u64; 0] = [];
        // Build [42, 99]: cons(99, []) then cons(42, that).
        let inner = alloc_test_cons(((99u64) << 3) | TAG_INT as u64, EMPTY_LIST_BITS as u64);
        let list = alloc_test_cons(((42u64) << 3) | TAG_INT as u64, inner);
        let mut out = [0u64; 2];
        assert_eq!(f(list, pin.as_ptr(), out.as_mut_ptr()), 1);
        assert_eq!(out[0], ((42u64) << 3) | TAG_INT as u64);
        assert_eq!(out[1], inner);

        // Non-list inputs must miss.
        let mut out2 = [0u64; 2];
        assert_eq!(
            f(EMPTY_LIST_BITS as u64, pin.as_ptr(), out2.as_mut_ptr()),
            0
        );
        let mut out3 = [0u64; 2];
        let int_msg = ((7u64) << 3) | TAG_INT as u64;
        assert_eq!(f(int_msg, pin.as_ptr(), out3.as_mut_ptr()), 0);
    }

    /// fz-puj.48 (X7) — when emit_decision returns Err the closure used to
    /// bail out leaving the body half-finished, which tripped a cranelift
    /// `remove_constant_phis: entry block unknown` panic. The error path now
    /// must seal the function body cleanly so the CodegenError propagates.
    #[test]
    fn decision_matcher_unsupported_kind_surfaces_clean_codegen_error() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        // Pattern::Binary specialises to SwitchKind::Binary, which needs
        // the fz_matcher_eq_bytes runtime helper. In this unit-test mode
        // the runtime isn't linked (matcher_eq_bytes_id = None), so the
        // emitter must surface a clean CodegenError rather than panic.
        let pat = AstPattern::Binary(b"hi".to_vec());
        let clauses = vec![clause_with(pat, vec![])];
        let fid = declare_matcher(&mut jmod, "dm_unsupported_kind").unwrap();
        let err = emit_matcher_body_from_decision(
            &mut jmod, &mut fbctx, fid, &m, &tuple_ids, &pinned, &clauses, None, None,
        )
        .unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("fz_matcher_eq_bytes") || msg.contains("Binary"),
            "error names the missing runtime helper: {}",
            msg
        );
    }

    #[test]
    fn decision_matcher_bitstring_pattern_currently_misses_via_per_row() {
        let (mut jmod, mut fbctx) = make_jit();
        let m = empty_module();
        let tuple_ids = HashMap::new();
        let pinned: Vec<(String, Var)> = Vec::new();
        let clauses = vec![
            clause_with(AstPattern::Bitstring(vec![]), vec![]),
            clause_with(AstPattern::Wildcard, vec![]),
        ];
        let f = build_decision_matcher(
            &mut jmod,
            &mut fbctx,
            &m,
            &tuple_ids,
            &pinned,
            &clauses,
            "dm_bitstring_current_miss",
        );
        let pin: [u64; 0] = [];
        let mut out = [0u64; 0];
        assert_eq!(
            f(0, pin.as_ptr(), out.as_mut_ptr()),
            2,
            "bitstring patterns currently miss in PerRow and fall through"
        );
    }
}
