IO.inspect(Enum.max([3, 1, 2]))
IO.inspect(Enum.min([3, 1, 2]))
IO.inspect(Enum.min_max([3, 1, 2]))
IO.inspect(Enum.max_by(["a", "bbb", "cc"], fn s -> String.length(s) end))
IO.inspect(Enum.min_by(["a", "bbb", "cc"], fn s -> String.length(s) end))
IO.inspect(Enum.sort_by(["bbb", "a", "cc"], fn s -> String.length(s) end))
IO.inspect(Enum.join([1, 2, 3], "-"))
IO.inspect(Enum.join(["a", "b"]))
IO.inspect(Enum.sum([1, 2, 3]))
IO.inspect(Enum.sum_by([1, 2, 3], fn x -> x * 2 end))
IO.inspect(Enum.product([2, 3, 4]))
IO.inspect(Enum.fetch([1, 2, 3], 1))
IO.inspect(Enum.fetch([1, 2, 3], 9))
IO.inspect(Enum.at([1, 2, 3], 1))
IO.inspect(Enum.at([1, 2, 3], 9, :none))
IO.inspect(Enum.concat([[1, 2], [3]]))
IO.inspect(Enum.concat([1], [2]))
IO.inspect(Enum.dedup([1, 1, 2, 2, 1]))
IO.inspect(Enum.count_until([1, 2, 3, 4], 2))
IO.inspect(Enum.zip([1, 2], ["a", "b"]))
IO.inspect(Enum.unzip([{1, "a"}, {2, "b"}]))
IO.inspect(Enum.chunk_every([1, 2, 3, 4, 5], 2))
IO.inspect(Enum.chunk_by([1, 1, 2, 3, 3], fn x -> x end))
IO.inspect(Enum.uniq([1, 2, 1, 3]))
IO.inspect(Enum.frequencies(["a", "b", "a"]))
IO.inspect(Enum.group_by([1, 2, 3, 4], fn x -> rem(x, 2) end))
