kw = [{:a, 1}, {:b, 2}, {:a, 3}]
IO.inspect(Keyword.get(kw, :a))
IO.inspect(Keyword.get(kw, :z, :none))
IO.inspect(Keyword.fetch(kw, :b))
IO.inspect(Keyword.fetch(kw, :z))
IO.inspect(Keyword.get_values(kw, :a))
IO.inspect(Keyword.keys(kw))
IO.inspect(Keyword.values(kw))
IO.inspect(Keyword.has_key?(kw, :b))
IO.inspect(Keyword.delete(kw, :a))
IO.inspect(Keyword.delete_first(kw, :a))
IO.inspect(Keyword.put(kw, :a, 9))
IO.inspect(Keyword.put_new(kw, :c, 4))
IO.inspect(Keyword.take(kw, [:a]))
IO.inspect(Keyword.drop(kw, [:a]))
IO.inspect(Keyword.pop(kw, :a))
IO.inspect(Keyword.keyword?(kw))
IO.inspect(Keyword.keyword?([1, 2]))
