IO.inspect(String.contains?("hello", ""))
IO.inspect(String.contains?("", ""))
IO.inspect(String.count("hello", ""))
IO.inspect(String.count("", ""))
IO.inspect(String.count("é", ""))
IO.inspect(String.split("hello", ""))
IO.inspect(String.split("", ""))
IO.inspect(String.split("é", ""))
IO.inspect(String.split("日本", ""))
IO.inspect(String.replace("hello", "", "-"))
IO.inspect(String.replace("", "", "-"))
IO.inspect(String.replace("é", "", "-"))
IO.inspect(String.replace("hello", "", ""))
