IO.inspect(String.length("héllo"))
IO.inspect(String.starts_with?("hello", "he"))
IO.inspect(String.starts_with?("hello", "xx"))
IO.inspect(String.ends_with?("hello", "lo"))
IO.inspect(binary_slice("hello world", 6, 5))
IO.inspect(String.replace_prefix("hello", "he", "HE"))
IO.inspect(String.replace_suffix("hello", "lo", "LO"))
IO.inspect(String.replace_leading("aaabc", "a", "X"))
IO.inspect(String.replace_trailing("abccc", "c", "Y"))
IO.inspect(String.trim("  hi  "))
IO.inspect(String.trim_leading("  hi"))
IO.inspect(String.trim_trailing("hi  "))
IO.inspect(String.upcase("héllo", :ascii))
IO.inspect(String.downcase("HÉLLO", :ascii))
IO.inspect(String.duplicate("ab", 3))
IO.inspect(String.contains?("hello", "ell"))
IO.inspect(length(String.split("banana", "an")) - 1)
IO.inspect(String.split("a,b,c", ","))
IO.inspect(String.replace("a-b-c", "-", "+"))
IO.inspect(String.codepoints("héllo"))
IO.inspect(String.next_codepoint("héllo"))
IO.inspect(String.valid?("hi"))
IO.inspect([97, 98, 99], charlists: :as_lists)
IO.inspect(String.reverse("héllo"))
IO.inspect(String.first("héllo"))
IO.inspect(String.last("héllo"))
